Update project documentation
openHPI/xikolo-ios pull request #813
Opened 2020-08-14 10:20 UTC by mathebox

As part of our Documentation Friday initiative

2020-09-16 13:50 UTC, tobiasrohloff requested changes

2020-09-16 13:50 UTC, tobiasrohloff commented on CONTRIBUTING.md
> +- For fewer unneccessary whitespace changes, please set both checkboxes in `Xcode > Preferences > Text Editing` regarding whitespaces
That might become outdated unnoticed with a new Xcode version. Better name these 2 settings explicitly.

2020-09-16 13:50 UTC, tobiasrohloff commented on CONTRIBUTING.md
> +- Use Unix-style line endings (LF)
Where can I configure this? Probably at the same place as the options above, but that is not clear.

2020-09-16 13:50 UTC, tobiasrohloff commented on CONTRIBUTING.md
> +We use [R.swift](https://github.com/mac-cain13/R.swift) to avoid static string in the codebase.
```suggestion
We use [R.swift](https://github.com/mac-cain13/R.swift) to avoid static strings in the codebase.
```

2020-09-16 13:50 UTC, tobiasrohloff commented on CONTRIBUTING.md
>  One thing we can't enforce with R.swift is not to omit `self`. We prefer writing `self` explicitly because we believe this helps to distinguish between member attributes and local variabels.
You could point to an example in the codebase.

2020-09-16 13:50 UTC, tobiasrohloff commented on CONTRIBUTING.md
>  ```
```suggestion
```swift
```

2020-09-16 13:50 UTC, tobiasrohloff commented on README.md
>      iOS application for openHPI, openSAP, mooc.house, lernen.cloud and OpenWHO
```suggestion
    iOS application for the HPI MOOC Platform
```

Better name and link the growing number of brands in a list somewhere below.

2020-09-16 13:50 UTC, tobiasrohloff commented on README.md
> +For the overall architecture, we follow a plain MVC approach. However we make use of some reactive programming by using futures and promises provided by BrightFutures.
Maybe link `BrightFutures`.

2020-09-16 13:50 UTC, tobiasrohloff commented on README.md
> +### Naming schema
```suggestion
### Naming Schema
```

2020-09-16 13:50 UTC, tobiasrohloff commented on README.md
> +The Common module hold the core functionality of the app, which are required in all tragets. It includes the CoreData models, API abstraction layer, common functionalities and generic helpers.
```suggestion
The `Common` module holds the core functionality of the app, which is required in all targets. It includes the CoreData models, API abstraction layer, common functionalities and generic helpers.
```

2020-09-16 13:50 UTC, tobiasrohloff commented on README.md
> +The `Binge` module provides a custom video player which in constrast to `AVPlayerViewController` allows entering the full screen mode programtically and provides controls for changing the playback ra
```suggestion
The `Binge` module provides a custom video player which in contrast to `AVPlayerViewController` allows entering the full-screen mode programmatically and provides controls for changing the playback rate.
```

2020-09-16 13:50 UTC, tobiasrohloff commented on README.md
> +The `Stockpile` module is responsible for retrieving resources from the backend and synchronizing them with the local storage. It is capabile of sending network requests depending on the protocol of
```suggestion
The `Stockpile` module is responsible for retrieving resources from the backend and synchronizing them with the local storage. It is capable of sending network requests depending on the protocol of the backend. 
```

2020-09-16 13:50 UTC, tobiasrohloff commented on CONTRIBUTING.md
>  Check out the [good first issues](https://github.com/openHPI/xikolo-ios/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) or any other unsassigned issue and submit a pull request when you
```suggestion
Check out the [good first issues](https://github.com/openHPI/xikolo-ios/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) or any other unassigned issue and submit a pull request when you are ready.
```

2020-09-16 13:50 UTC, tobiasrohloff commented on CONTRIBUTING.md
> +- `bundle exec fastlane export_localizations`: Export localizations and strip unwanted strings, that excluded by BartyCrouch
```suggestion
- `bundle exec fastlane export_localizations`: Export localizations and strip unwanted strings, that are excluded by BartyCrouch
```

2020-09-16 13:50 UTC, tobiasrohloff commented on README.md
> +The `iOS` target is the main applciation.
```suggestion
The `iOS` target is the main application.
```

2020-09-16 13:50 UTC, tobiasrohloff commented on RELEASE.md
> +   Enter values for `apple_id` (your Apple developer account) and `itunes_connect_id` (your Apple Account with access to AppStoreConnect). Those two could be the same Apple account.
```suggestion
   Enter values for `apple_id` (your Apple developer account) and `itunes_connect_id` (your Apple account with access to AppStoreConnect). Those two could be the same Apple account.
```

2020-09-16 13:50 UTC, tobiasrohloff commented on RELEASE.md
> +You have to be part of out core dev team to do this.
```suggestion
You have to be part of our core dev team to do this.
```

2020-09-16 13:50 UTC, tobiasrohloff commented on RELEASE.md
> +   The keyfile is managed by the openHPI team and should never be made public or added to the repository.
```suggestion
   The keyfile is managed by our core dev team and should never be made public or added to the repository.
```

2020-09-16 13:50 UTC, tobiasrohloff commented on RELEASE.md
> +There is a fastlane command for each step. One for all flavor and one for each flavor (suffix: `_flavorname`)
```suggestion
There is a fastlane command for each step. One for all flavors and one for each flavor (suffix: `_flavorname`)
```

2020-09-16 13:50 UTC, tobiasrohloff commented on RELEASE.md
> +1. Create a github release (incl. git tag) for the release via `fastlane tag_release`
```suggestion
1. Create a GitHub release (incl. git tag) for the release via `fastlane tag_release`
```

2020-09-17 09:10 UTC, tobiasrohloff requested changes

2020-09-17 09:10 UTC, tobiasrohloff commented on CONTRIBUTING.md
> +  - Choose `Unicode (UTF-8)` for `Defautl Text Encoding`
```suggestion
  - Choose `Unicode (UTF-8)` for `Default Text Encoding`
```

2020-09-17 09:10 UTC, tobiasrohloff commented on CONTRIBUTING.md
> +  - Check box for `Including whitespac-eonly lines`
```suggestion
  - Check box for `Including whitespace-only lines`
```

2020-09-17 09:10 UTC, tobiasrohloff commented on CONTRIBUTING.md
> +  - Check box for `Automatically trim trailing whitespace`
```suggestion
  - Checkbox for `Automatically trim trailing whitespace`
```
Same below.

2020-09-17 10:33 UTC, mathebox commented on CONTRIBUTING.md
> +  - Check box for `Automatically trim trailing whitespace`
It's checking the box ;)

2020-09-17 10:53 UTC, tobiasrohloff commented on CONTRIBUTING.md
> +  - Check box for `Automatically trim trailing whitespace`
haha true

2020-09-17 10:54 UTC, tobiasrohloff approved these changes

2020-09-18 14:23 UTC, merged